"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33663).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json."""
import base64
import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
from jose import jwk, jwt
from jose.exceptions import JWKError

def _ec_ssh_public_key() -> bytes:
    """Build a real OpenSSH-format ECDSA public key (ecdsa-sha2-nistp256)."""
    key = ec.generate_private_key(ec.SECP256R1())
    der = key.public_key().public_bytes(encoding=serialization.Encoding.DER, format=serialization.PublicFormat.SubjectPublicKeyInfo)
    return b'ecdsa-sha2-nistp256 ' + base64.b64encode(der) + b' user@host'

def test_ghsa_6c5p_j8vq_pqhj_fix_pinning():
    """OpenSSH ECDSA public key must be rejected as an HMAC secret (JWKError)."""
    with pytest.raises(JWKError):
        jwk.construct(_ec_ssh_public_key(), algorithm='HS256')
