"""Generated by ai-test-harness for python-jose 3.4.0 (category: unit).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json."""
import time
import pytest
from cryptography.hazmat.primitives.asymmetric import rsa
from jose import jwt, jwe, jws, JWTError, JWSError
from jose.exceptions import ExpiredSignatureError, JWSSignatureError
from jose.utils import base64url_encode, base64url_decode

def _rsa_key():
    return rsa.generate_private_key(public_exponent=65537, key_size=2048)

def test_jwt_encode_hs256_structure():
    """jwt.encode with HS256 produces a three-part token whose header is alg=HS256."""
    token = jwt.encode({'sub': 'u1'}, 'secret', algorithm='HS256')
    parts = token.split('.')
    assert len(parts) == 3
    header = jwt.get_unverified_header(token)
    assert header['alg'] == 'HS256'

def test_jwt_decode_roundtrip_hs256():
    """jwt.decode returns the original claims for a valid HS256 token."""
    claims = {'sub': 'u1', 'name': 'Alice'}
    token = jwt.encode(claims, 'secret', algorithm='HS256')
    assert jwt.decode(token, 'secret', algorithms=['HS256']) == claims

def test_jwt_decode_wrong_key_raises_jwt_error():
    """jwt.decode raises JWTError when the key does not match the signature."""
    token = jwt.encode({'sub': 'u1'}, 'secret-a', algorithm='HS256')
    with pytest.raises(JWTError):
        jwt.decode(token, 'secret-b', algorithms=['HS256'])

def test_jwt_decode_expired_raises_expired_signature_error():
    """jwt.decode raises ExpiredSignatureError for a token past its exp claim."""
    now = int(time.time())
    token = jwt.encode({'sub': 'u1', 'exp': now - 100}, 'secret', algorithm='HS256')
    with pytest.raises(ExpiredSignatureError):
        jwt.decode(token, 'secret', algorithms=['HS256'])
