"""Generated by ai-test-harness (agent mode) for python-jose 3.4.0 (category: cve, issue CVE-2024-33664).
Candidate tests: not yet human-reviewed. Provenance in ../manifest.json."""
import json
import zlib
import pytest
from jose import jwe
from jose.exceptions import JWEError

def _b64url(data: bytes) -> str:
    import base64
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode('ascii')

def _make_bomb_token() -> str:
    """Build a valid compressed JWE whose plaintext is larger than the 250 KiB limit."""
    key = 'asecret128bitkey'
    header = {'alg': 'dir', 'enc': 'A128GCM', 'zip': 'DEF'}
    encoded_header = _b64url(json.dumps(header).encode('utf-8'))
    plaintext = b'A' * (300 * 1024)
    compressed = zlib.compress(plaintext, 9)
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    aesgcm = AESGCM(key.encode('utf-8'))
    iv = b'\x00' * 12
    ciphertext_and_tag = aesgcm.encrypt(iv, compressed, encoded_header.encode('utf-8'))
    ciphertext = ciphertext_and_tag[:-16]
    auth_tag = ciphertext_and_tag[-16:]
    return '.'.join([encoded_header, '', _b64url(iv), _b64url(ciphertext), _b64url(auth_tag)])

def test_ghsa_cjwg_qfpm_7377_fix_pinning():
    """Decompressing a JWE whose plaintext exceeds the size limit must raise JWEError."""
    token = _make_bomb_token()
    with pytest.raises(JWEError):
        jwe.decrypt(token, 'asecret128bitkey')

def test_ghsa_cjwg_qfpm_7377_exposure():
    """A caller passing an attacker-supplied token to jwe.decrypt must not get a huge plaintext back."""
    token = _make_bomb_token()
    try:
        result = jwe.decrypt(token, 'asecret128bitkey')
        assert result is None or len(result) <= 250 * 1024, f'decrypt returned {len(result)} bytes of decompressed data' if result else ''
        assert False, 'decrypt should have raised JWEError for an oversized decompressed payload' if result is not None else ''
    except JWEError:
        pass
